### ISSUE TITLE
IFX007T & BLDCSHIELDIFX007T won't drive sensorless motor

### ISSUE THREAD

**Issue by davidcyr2000** [Infineon/IFX007T-Motor-Control#19]
We have reviewed all available documentation including the sample code from the Arduino website (https://www.arduino.cc/reference/en/libraries/ifx007t-motor-control/). Version 1.1.0 drives our motor, while the Github Version 1.0.0 does nothing to the motor, even though the "find poles" program does work properly. (https://github.com/Infineon/IFX007T-Motor-Control/)

With some added debugging statements and an ammeter in the circuit, we can marginally run the sensorless BLDC motor that is rated at max 10A at 12V, but only with no load so far.  However, it is very rough and pulls excessive current on start-up (13A) for about 2 seconds, then settles down to 5.5A.  This is using Version 1.1.0 code available on the Arduino website.  Version 1.0.0 from Github doesn't run the motor at all.

The sample code was put into folder MyMotor as described in the documentation:
MyMotor.ino
IFX007T-Motor-Control.h
IFX007T-Motor-Control.cpp
Documentation referenced:
https://www.infineon.com/cms/en/product/evaluation-boards/bldc-shield_ifx007t/#!documents
https://www.infineon.com/dgdl/Infineon-IFX007T-DS-v01_00-EN.pdf?fileId=5546d46265f064ff0166433484070b75
https://www.mouser.com/datasheet/2/196/Infineon-Motor_Control_Shield_with_IFX007T_for_Ard-1551136.pdf
https://community.infineon.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=IFX007T

The only code changes were:
 - the number of pole pairs to 2 based on running "Find_polepairs.ino"
 - debug statement uncommented
 - SensingMode = 0 for the sensorless motor
 - added 2 Serial.print() statements in "loop"
 
The electrolytic capacitor heats up very quickly; faster and hotter than the MOSFETs, to the extent that we won't run the ESC for more than 30 seconds for fear the capacitor will explode.
 
Varying the parameters with the Arduino IDE "Serial Monitor" has little effect on the 5.5A current draw or the RPM.
 
A most curious observation is the effect that 2 Serial.print() statements have on the way the motor runs.  With two print statements in the Arduino MyMotor.ino "loop", the motor runs at 5.5A, but with these two print statements commented out, the motor doesn't run.  It just pulls 13A @ 4V (because it draws down the 10A 13V power supply) and never stabilizes at 5.5A as it does when the print statements are included.  It also only runs IF there is an ammeter in series with the power supply.  Remove either the Serial.print statements or the ammeter, and the motor struggles to start, dragging down the power supply voltage, and hard stops after about 3 seconds, still pulling 13A.
 
Questions:
Is there any tool to exercise the motor that determines what the various parameters should be?
Is there a Windows GUI to change the parameters and RPM/duty cycle?
Can you suggest how we can properly run the motor?
Is there a document that explains the function of the various parameters?   
e.g.   0.01 has no meaning and there is no explanation how to set these values
PI_Reg_P = 0.01;  // P value for the PI-RPM regulator
PI_Reg_I = 0.01;   // I value for the PI-RPM regulator 

Environment: Windows 10, Arduino IDE Version 1.8.16, Arduino UNO (and 2560 - same results), low resistance (0.05ohms) & low inductance pump motor rated at 12V, 10A and 10,000 RPM.

Thank you for any help you can provide,
David Cyr

**Comment by BrixInMotion** [comment]
Hi David,

sensor less BLDC motor control with the IFX007t shield is tricky as you might have seen from previous issues. This is also the reason why we removed the BEMF example until there is a new Software available. 

To your questions:
1) Documentation for the BEMF mode can be found in the deleted example folder: https://github.com/Infineon/IFX007T-Motor-Control/tree/V1.1.0/examples/IFX007_BLDC_BEMF
2) No there is no GUI unfortunately.
3) Regarding the Parameter PI_Reg_P and PI_Reg_I: These are values for a PI-regulator. If you are not familiar with PID control, I can recommend this video series: https://www.youtube.com/playlist?list=PLn8PRpmsu08pQBgjxYFXSsODEF3Jqmm-y

In order to get your motor running, I would first recommend to neglect the RPM regulation part as this makes it just more complicated for now. Only use  `setBLDCDutyCyclespeed()` in order to directly set the duty cycle.  In the BEMF Readme you will also find a plot with typical current values that can be achieved, so 5.5A without load is already way too much.
I have also an assumption for your curious observation: 
* Serial.prints() last very long. So avoid them wherever possible when running a BLDC motor. If they are necessary, keep them short and try to increase the baud rate (e.g. 250.000).
* Your Amp meter may limit the current. So obviously it is helpful for the motor if the current is limited externally. One reason might be the fast saturation of the iron with high currents.

Best Regards,
Kilian

**Comment by davidcyr2000** [comment]
Hi Kilian,

Thanks for the frank comments about sensorless.  The program Infineon has removed from Github is identical to the code at the Arduino website, which they call Version 1.1.0.  It only drives the motor with the 2 Serial.print() statements AND the ammeter.

You mentioned “until there is a new Software available”.  Should we expect something in the near term?  Is something planned or in the works?  Basically I have given up on the Infineon demo board given the poor performance of our motor, the lack of a GUI for parameter tuning and no instructions on how to tune the motor parameters.

If there are tools coming, please indicate what we should expect and when.

Thanks,

David Cyr

**Comment by BrixInMotion** [comment]
Hi David,

sorry for the misleading phrase, currently there is nothing planned for the near future regarding sensorless BLDC drive. However BLDC control with hallsensor and DC motor control should work properly with the provided library on the IFX007t shield.

Best Regards,
Kilian

**Comment by tzha934** [comment]
> 

Hi Kilian, 

I am currently following BEMF Tuning and I just want to check with you which pins I should be hooking up with the oscilloscope like in your image.

Best Regards,

Aaron

**Comment by BrixInMotion** [comment]
Hi Aaron,

In the Oszi pictures, the probes are connected like:
Ch1: Output phase U to the motor
Ch2: V_neutral on pin A0 of Arduino
Ch3: BEMF voltage on pin A3 of Arduino
Ch4: pin 12 of Arduino as a debugging pin. You may need to uncomment / add some code to use this as an indicator where the program is at the moment.

Best Regards,
Kilian

**Comment by tzha934** [comment]
Dear Killian,

Thank you very much! 

Best Regards,
Aaron
