### ISSUE TITLE
is an FOC implementation possible

### ISSUE THREAD

**Issue by ddieffen** [Infineon/IFX007T-Motor-Control#5]
Hello,

Has anyone tried to implement an FOC algorithm using the Arduino IDE but maybe something more powerfull than an Uno, like a Due ?

Best regards

**Comment by djaumann** [comment]
Hey @ddieffen,

as far as I know no one has implemented a FOC so far, but I'm also not sure if the hardware is supporting a FOC. But I will get in contact with the application engineer and will let you know if this is possible or was already done.

The performance of the Arduino could might be a problem as well, but that depends on the required code for the FOC and the timing of all the measurements during the FOC. But I will let you know more as far as I have a response.

Best Regards,
Dominik

**Comment by srehb** [comment]
Hi,

@djaumann did anything turn out from your investigation?
I would be interested as well if a combination of the IFX007 shield with an Arudino Uno or XMC4700 would be capable of realizing a fully field-oriented control for a PMSM.

Is the IFX007T IC generally applicable for this, or can you suggest another shield for realizing an evaluation setup?

Best regards,
Sebastian

**Comment by djaumann** [comment]
Hey @srehb and @ddieffen,

I'm very sorry for the late response ...
I was in contact with a colleague who was involved in the design of the board and he told me that it is not possible with a normal Arduino (due to the lack of computation power). He also told me that a FOC with the IFX007T could get quite tricky and said it is probably easier to use the new TLE9563-BLDC-Shield with a powerful Arduino (like the Due for example). Here you can find more information about the board: https://www.infineon.com/cms/de/product/evaluation-boards/bldc-shield_tle956x/.

I hope that helps you!
If you have further questions please let me know.

Best regards,
Dominik
